version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: mi-postgres-container
    environment:
      POSTGRES_USER: martin
      POSTGRES_PASSWORD: martin
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app-backend:
    build: .
    container_name: mi-backend-java
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/todo_db
      SPRING_DATASOURCE_USERNAME: martin
      SPRING_DATASOURCE_PASSWORD: martin
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

volumes:
  postgres_data: